apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whitespace
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: blue-green/
    repoURL: 'https://github.com/slovink/argocd-bluegreen.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: '0.1'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
